// <auto-generated />
using Bobbins.Links.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bobbins.Links.Migrate.Migrations
{
    [DbContext(typeof(LinkContext))]
    [Migration("20171109183440_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Bobbins.Links.Data.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentCount");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<int>("DownVoteCount");

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.Property<int>("UpVoteCount");

                    b.Property<string>("Url")
                        .HasMaxLength(256);

                    b.Property<string>("User")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Bobbins.Links.Data.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LinkId");

                    b.Property<string>("User")
                        .HasMaxLength(16);

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LinkId", "User")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Bobbins.Links.Data.Vote", b =>
                {
                    b.HasOne("Bobbins.Links.Data.Link", "Link")
                        .WithMany("Votes")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
